import:
  - ../common

normalization: softmax
###################
# Training Config
###################
num_workers: 8
batch_size: 16
epochs: 200
lr: 1.0e-2
weight_decay: 0.0


resnet_kws:
  pretrained: false
  progress: true
