import:
  - ../common

normalization: softmax
num_classes: 2
data_len: 300

###################
# Training Config
###################
num_workers: 8
batch_size: 16
epochs: 200
lr: 1.0e-2
weight_decay: 0.0

###################
# Model Config
###################
patch_sizes: 32
patch_strides: 16
clip_pretrained: false
checkpoint: false
checkpoint_nchunks: 2
